device-sample: optimize recipe
* Makefile does not support the use of the CC environment variable,
  so use make CC="${CC}"
* when LDFLAGS is involved in compilation, the following error will occur:
  `undefined reference to `vtable for __cxxabiv1::__class_type_info'`
  provide a workaround to fix this error, remove '-Wl,--as-needed' option
  from LDFLAGS

Signed-off-by: lixiaoyong <lixiaoyong19@huawei.com>