scripts/requirements-doc.txt: Update dependency versions
* The current requirements-doc.txt will install Sphinx version 3.3.
  When this version builds the document, the following errors will occur:
  ImportError: cannot import name 'Union' from 'types'

* Therefore, update the version of sphinx in requirememt to 5.1
  and related dependencies to fix the problem.

Signed-off-by: dengpengfei <1652695505@qq.com>